version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
